# kestrel:
#   image: frannsoftdev/docker-nginx-test
#   expose:
#     - "5000"
# nginx:
#   build: ./nginx
#   links:
#     - kestrel:kestrel
#   ports:
#     - "80:80"

version: "3"

services:
  kestrel:
    build:
      context: .
      dockerfile: Dockerfile
    image: kestrel
    container_name: kestrel
    restart: unless-stopped
    networks:
      - app-network

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - web-root:/app/dockernginxtut
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - kestrel
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/app/dockernginxtut
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/app/dockernginxtut --email frannsoftdev@outlook.com --agree-tos --no-eff-email --staging -d jackandwesgamingadventures.com  -d www.jackandwesgamingadventures.com

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/franndotexe/docker-nginx-test/
      o: bind

networks:
  app-network:
    driver: bridge
